package main;
// Generated 4 oct. 2022 10:39:04 by Hibernate Tools 6.0.2.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Seguro generated by hbm2java
 */
public class Seguro implements java.io.Serializable {

	private Integer idSeguro;
	private String nif;
	private String nombre;
	private String ape1;
	private String ape2;
	private Integer edad;
	private Integer sexo;
	private Boolean casado;
	private Integer numHijos;
	private Boolean embarazada;
	private Boolean oftalmologia;
	private Boolean dental;
	private Boolean fecundacionInVitro;
	private Boolean corazon;
	private Boolean estomacal;
	private Boolean rinyones;
	private Boolean alergia;
	private String nombreAlergia;
	private Timestamp fechaCreacion;
	private Set asistenciamedicas = new HashSet(0);

	public Seguro() {
	}

	public Seguro(String nif, String nombre) {
		this.nif = nif;
		this.nombre = nombre;
	}

	public Seguro(Integer idSeguro, String nif, String nombre, String ape1, String ape2, Integer edad, Integer numHijos,
			Timestamp fechaCreacion) {
		super();
		this.idSeguro = idSeguro;
		this.nif = nif;
		this.nombre = nombre;
		this.ape1 = ape1;
		this.ape2 = ape2;
		this.edad = edad;
		this.numHijos = numHijos;
		this.fechaCreacion = fechaCreacion;

	}

	public Seguro(String nif, String nombre, String ape1, String ape2, Integer edad, Integer sexo, Boolean casado,
			Integer numHijos, Boolean embarazada, Boolean oftalmologia, Boolean dental, Boolean fecundacionInVitro,
			Boolean corazon, Boolean estomacal, Boolean rinyones, Boolean alergia, String nombreAlergia,
			Timestamp fechaCreacion, Set asistenciamedicas) {
		this.nif = nif;
		this.nombre = nombre;
		this.ape1 = ape1;
		this.ape2 = ape2;
		this.edad = edad;
		this.sexo = sexo;
		this.casado = casado;
		this.numHijos = numHijos;
		this.embarazada = embarazada;
		this.oftalmologia = oftalmologia;
		this.dental = dental;
		this.fecundacionInVitro = fecundacionInVitro;
		this.corazon = corazon;
		this.estomacal = estomacal;
		this.rinyones = rinyones;
		this.alergia = alergia;
		this.nombreAlergia = nombreAlergia;
		this.fechaCreacion = fechaCreacion;
		this.asistenciamedicas = asistenciamedicas;
	}

	public Integer getIdSeguro() {
		return this.idSeguro;
	}

	public void setIdSeguro(Integer idSeguro) {
		this.idSeguro = idSeguro;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApe1() {
		return this.ape1;
	}

	public void setApe1(String ape1) {
		this.ape1 = ape1;
	}

	public String getApe2() {
		return this.ape2;
	}

	public void setApe2(String ape2) {
		this.ape2 = ape2;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Integer getSexo() {
		return this.sexo;
	}

	public void setSexo(Integer sexo) {
		this.sexo = sexo;
	}

	public Boolean getCasado() {
		return this.casado;
	}

	public void setCasado(Boolean casado) {
		this.casado = casado;
	}

	public Integer getNumHijos() {
		return this.numHijos;
	}

	public void setNumHijos(Integer numHijos) {
		this.numHijos = numHijos;
	}

	public Boolean getEmbarazada() {
		return this.embarazada;
	}

	public void setEmbarazada(Boolean embarazada) {
		this.embarazada = embarazada;
	}

	public Boolean getOftalmologia() {
		return this.oftalmologia;
	}

	public void setOftalmologia(Boolean oftalmologia) {
		this.oftalmologia = oftalmologia;
	}

	public Boolean getDental() {
		return this.dental;
	}

	public void setDental(Boolean dental) {
		this.dental = dental;
	}

	public Boolean getFecundacionInVitro() {
		return this.fecundacionInVitro;
	}

	public void setFecundacionInVitro(Boolean fecundacionInVitro) {
		this.fecundacionInVitro = fecundacionInVitro;
	}

	public Boolean getCorazon() {
		return this.corazon;
	}

	public void setCorazon(Boolean corazon) {
		this.corazon = corazon;
	}

	public Boolean getEstomacal() {
		return this.estomacal;
	}

	public void setEstomacal(Boolean estomacal) {
		this.estomacal = estomacal;
	}

	public Boolean getRinyones() {
		return this.rinyones;
	}

	public void setRinyones(Boolean rinyones) {
		this.rinyones = rinyones;
	}

	public Boolean getAlergia() {
		return this.alergia;
	}

	public void setAlergia(Boolean alergia) {
		this.alergia = alergia;
	}

	public String getNombreAlergia() {
		return this.nombreAlergia;
	}

	public void setNombreAlergia(String nombreAlergia) {
		this.nombreAlergia = nombreAlergia;
	}

	public Timestamp getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Timestamp fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set getAsistenciamedicas() {
		return this.asistenciamedicas;
	}

	public void setAsistenciamedicas(Set asistenciamedicas) {
		this.asistenciamedicas = asistenciamedicas;
	}

	@Override
	public String toString() {
		return "Seguro [idSeguro=" + idSeguro + ", nif=" + nif + ", nombre=" + nombre + ", ape1=" + ape1 + ", ape2="
				+ ape2 + ", edad=" + edad + ", sexo=" + sexo + ", casado=" + casado + ", numHijos=" + numHijos
				+ ", embarazada=" + embarazada + ", oftalmologia=" + oftalmologia + ", dental=" + dental
				+ ", fecundacionInVitro=" + fecundacionInVitro + ", corazon=" + corazon + ", estomacal=" + estomacal
				+ ", rinyones=" + rinyones + ", alergia=" + alergia + ", nombreAlergia=" + nombreAlergia
				+ ", fechaCreacion=" + fechaCreacion + ", asistenciamedicas=" + asistenciamedicas + "]";
	}

}
